spring:
  datasource:
    url: jdbc:h2:mem:bidydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop    # 테이블 자동 생성
    show-sql: true       # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 출력

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true