spring.application.name=MyProject

spring.datasource.url=jdbc:mysql://localhost:3306/MyProject?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=dbalsdl772799
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#3306 == mysql port

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


